# Generated by Django 5.1.7 on 2025-03-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=10)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pedentes'), ('pago', 'Pago')], max_length=20)),
            ],
        ),
    ]
